/**
 * Realistic seed data for the Aegion Dashboard.
 * Used as fallback when backend API is unavailable.
 */

export const MOCK_STATS = {
    activeSessions: 3,
    sessionChange: 12,
    pendingProposals: 7,
    proposalChange: -2,
    totalDecisions: 184,
    decisionChange: 8,
    costToday: 2.47,
    costChange: -15,
    riskScore: 34,
    cacheHitRate: 68.4,
};

export const MOCK_COST_OVER_TIME = [
    { date: "Mar 11", openai: 1.2, anthropic: 0.8, google: 0.3, deepseek: 0.1 },
    { date: "Mar 12", openai: 1.5, anthropic: 0.7, google: 0.4, deepseek: 0.15 },
    { date: "Mar 13", openai: 0.9, anthropic: 1.1, google: 0.3, deepseek: 0.2 },
    { date: "Mar 14", openai: 1.8, anthropic: 0.6, google: 0.5, deepseek: 0.1 },
    { date: "Mar 15", openai: 2.1, anthropic: 0.9, google: 0.4, deepseek: 0.25 },
    { date: "Mar 16", openai: 1.4, anthropic: 1.3, google: 0.6, deepseek: 0.2 },
    { date: "Mar 17", openai: 1.0, anthropic: 0.5, google: 0.2, deepseek: 0.1 },
    { date: "Mar 18", openai: 1.6, anthropic: 0.8, google: 0.4, deepseek: 0.15 },
    { date: "Mar 19", openai: 2.3, anthropic: 1.0, google: 0.5, deepseek: 0.3 },
    { date: "Mar 20", openai: 1.9, anthropic: 0.7, google: 0.4, deepseek: 0.2 },
    { date: "Mar 21", openai: 1.1, anthropic: 1.2, google: 0.3, deepseek: 0.15 },
    { date: "Mar 22", openai: 1.7, anthropic: 0.9, google: 0.5, deepseek: 0.25 },
    { date: "Mar 23", openai: 2.0, anthropic: 1.1, google: 0.6, deepseek: 0.2 },
    { date: "Mar 24", openai: 1.3, anthropic: 0.6, google: 0.3, deepseek: 0.1 },
    { date: "Mar 25", openai: 1.8, anthropic: 0.8, google: 0.4, deepseek: 0.2 },
    { date: "Mar 26", openai: 2.4, anthropic: 1.0, google: 0.5, deepseek: 0.3 },
    { date: "Mar 27", openai: 1.6, anthropic: 0.7, google: 0.4, deepseek: 0.15 },
    { date: "Mar 28", openai: 1.2, anthropic: 1.1, google: 0.3, deepseek: 0.2 },
    { date: "Mar 29", openai: 1.9, anthropic: 0.9, google: 0.5, deepseek: 0.25 },
    { date: "Mar 30", openai: 2.1, anthropic: 0.8, google: 0.4, deepseek: 0.2 },
    { date: "Mar 31", openai: 1.5, anthropic: 1.2, google: 0.6, deepseek: 0.1 },
    { date: "Apr 01", openai: 1.7, anthropic: 0.6, google: 0.3, deepseek: 0.2 },
    { date: "Apr 02", openai: 2.2, anthropic: 1.0, google: 0.5, deepseek: 0.3 },
    { date: "Apr 03", openai: 1.4, anthropic: 0.7, google: 0.4, deepseek: 0.15 },
    { date: "Apr 04", openai: 1.1, anthropic: 0.9, google: 0.3, deepseek: 0.2 },
    { date: "Apr 05", openai: 1.8, anthropic: 0.8, google: 0.5, deepseek: 0.25 },
    { date: "Apr 06", openai: 2.0, anthropic: 1.1, google: 0.4, deepseek: 0.2 },
    { date: "Apr 07", openai: 1.3, anthropic: 0.6, google: 0.3, deepseek: 0.1 },
    { date: "Apr 08", openai: 1.6, anthropic: 0.9, google: 0.5, deepseek: 0.2 },
    { date: "Apr 09", openai: 1.9, anthropic: 0.7, google: 0.4, deepseek: 0.15 },
];

export const MOCK_DECISIONS_DISTRIBUTION = [
    { name: "Approved", value: 128, color: "#22c55e" },
    { name: "Rejected", value: 31, color: "#ef4444" },
    { name: "Pending", value: 7, color: "#eab308" },
    { name: "Deferred", value: 18, color: "#64748b" },
];

export const MOCK_RECENT_ACTIVITY = [
    {
        id: "evt-001",
        type: "proposal_approved",
        title: "Approved: Migrate auth to PKCE flow",
        actor: "council",
        timestamp: "2026-04-09T21:32:00Z",
        entityType: "proposal",
    },
    {
        id: "evt-002",
        type: "session_started",
        title: "Session started: Architecture Review Sprint",
        actor: "arpit",
        timestamp: "2026-04-09T21:15:00Z",
        entityType: "session",
    },
    {
        id: "evt-003",
        type: "sentinel_alert",
        title: "Sentinel: API key exposure detected in PR #47",
        actor: "sentinel",
        timestamp: "2026-04-09T20:58:00Z",
        entityType: "alert",
    },
    {
        id: "evt-004",
        type: "adr_created",
        title: "ADR-024: Switch from REST to gRPC for inter-service",
        actor: "arpit",
        timestamp: "2026-04-09T20:42:00Z",
        entityType: "adr",
    },
    {
        id: "evt-005",
        type: "decision_made",
        title: "Decision: Use Supabase Realtime over custom WebSocket",
        actor: "council",
        timestamp: "2026-04-09T19:30:00Z",
        entityType: "decision",
    },
    {
        id: "evt-006",
        type: "cost_alert",
        title: "Cost alert: Daily spend approaching 80% of budget",
        actor: "system",
        timestamp: "2026-04-09T18:15:00Z",
        entityType: "cost",
    },
    {
        id: "evt-007",
        type: "proposal_created",
        title: "New proposal: Add rate limiting to API gateway",
        actor: "arpit",
        timestamp: "2026-04-09T17:45:00Z",
        entityType: "proposal",
    },
    {
        id: "evt-008",
        type: "memory_stored",
        title: "Memory: User prefers TypeScript strict mode",
        actor: "system",
        timestamp: "2026-04-09T16:20:00Z",
        entityType: "memory",
    },
];

export const MOCK_PROPOSALS = [
    {
        id: "P-201",
        title: "Migrate authentication to PKCE flow",
        status: "approved",
        tier: "T2",
        councilScore: 0.92,
        createdAt: "2026-04-08T14:30:00Z",
        author: "arpit",
        summary: "Replace implicit grant with PKCE for better security in SPA.",
    },
    {
        id: "P-202",
        title: "Add rate limiting to API gateway",
        status: "pending",
        tier: "T1",
        councilScore: null,
        createdAt: "2026-04-09T17:45:00Z",
        author: "arpit",
        summary: "Implement token bucket rate limiting at 100 req/min per user.",
    },
    {
        id: "P-203",
        title: "Switch to gRPC for inter-service communication",
        status: "pending",
        tier: "T3",
        councilScore: null,
        createdAt: "2026-04-09T20:42:00Z",
        author: "arpit",
        summary: "Migrate REST endpoints between backend services to gRPC for type safety and performance.",
    },
    {
        id: "P-204",
        title: "Integrate Sentry for error tracking",
        status: "approved",
        tier: "T1",
        councilScore: 0.88,
        createdAt: "2026-04-07T10:15:00Z",
        author: "arpit",
        summary: "Add Sentry SDK to backend and frontend for production error monitoring.",
    },
    {
        id: "P-205",
        title: "Replace Redis with Dragonfly for caching",
        status: "rejected",
        tier: "T2",
        councilScore: 0.41,
        createdAt: "2026-04-06T08:00:00Z",
        author: "arpit",
        summary: "Evaluate Dragonfly as a drop-in Redis replacement for improved performance.",
    },
    {
        id: "P-206",
        title: "Implement WebSocket connection pooling",
        status: "pending",
        tier: "T2",
        councilScore: null,
        createdAt: "2026-04-09T12:00:00Z",
        author: "arpit",
        summary: "Pool WebSocket connections to reduce server resource usage under high load.",
    },
    {
        id: "P-207",
        title: "Add OpenTelemetry tracing",
        status: "approved",
        tier: "T2",
        councilScore: 0.95,
        createdAt: "2026-04-05T16:30:00Z",
        author: "arpit",
        summary: "Instrument all FastAPI endpoints with distributed tracing using OTEL.",
    },
];

export const MOCK_TIMELINE_EVENTS = [
    ...MOCK_RECENT_ACTIVITY,
    {
        id: "evt-009",
        type: "skill_executed",
        title: "Skill: Code complexity analyzer ran on /api/v1/council.py",
        actor: "system",
        timestamp: "2026-04-09T15:00:00Z",
        entityType: "skill",
    },
    {
        id: "evt-010",
        type: "proposal_rejected",
        title: "Rejected: Replace Redis with Dragonfly for caching",
        actor: "council",
        timestamp: "2026-04-09T14:30:00Z",
        entityType: "proposal",
    },
    {
        id: "evt-011",
        type: "session_ended",
        title: "Session ended: Backend Performance Optimization",
        actor: "arpit",
        timestamp: "2026-04-09T13:00:00Z",
        entityType: "session",
    },
    {
        id: "evt-012",
        type: "decision_made",
        title: "Decision: Keep PostgreSQL array columns over separate junction table",
        actor: "council",
        timestamp: "2026-04-09T11:45:00Z",
        entityType: "decision",
    },
    {
        id: "evt-013",
        type: "adr_superseded",
        title: "ADR-019 superseded by ADR-024: Service communication protocol",
        actor: "system",
        timestamp: "2026-04-09T10:30:00Z",
        entityType: "adr",
    },
    {
        id: "evt-014",
        type: "sentinel_alert",
        title: "Sentinel: Dependency vulnerability found in axios@1.12.0",
        actor: "sentinel",
        timestamp: "2026-04-08T22:00:00Z",
        entityType: "alert",
    },
    {
        id: "evt-015",
        type: "proposal_approved",
        title: "Approved: Add OpenTelemetry tracing",
        actor: "council",
        timestamp: "2026-04-08T20:15:00Z",
        entityType: "proposal",
    },
];

export const MOCK_ADRS = [
    {
        id: "ADR-024",
        title: "Switch from REST to gRPC for inter-service communication",
        status: "proposed",
        createdAt: "2026-04-09T20:42:00Z",
        author: "arpit",
        summary: "Use gRPC for internal service-to-service calls while keeping REST for external APIs.",
    },
    {
        id: "ADR-023",
        title: "Use Supabase Realtime over custom WebSocket server",
        status: "accepted",
        createdAt: "2026-04-08T14:00:00Z",
        author: "council",
        summary: "Leverage Supabase's built-in Realtime for push updates instead of maintaining a custom WS server.",
    },
    {
        id: "ADR-022",
        title: "Adopt FrugalGPT cascade pattern for cost optimization",
        status: "accepted",
        createdAt: "2026-04-06T10:00:00Z",
        author: "arpit",
        summary: "Route queries through cheaper models first (DeepSeek → Gemini → Claude) with confidence thresholds.",
    },
    {
        id: "ADR-021",
        title: "Store API keys client-side only",
        status: "accepted",
        createdAt: "2026-04-04T09:00:00Z",
        author: "arpit",
        summary: "Never persist user API keys in our database. Store in browser localStorage, inject via header.",
    },
    {
        id: "ADR-020",
        title: "Use pgvector for semantic search over Pinecone",
        status: "accepted",
        createdAt: "2026-04-02T15:00:00Z",
        author: "council",
        summary: "Keep vector embeddings in PostgreSQL via pgvector to avoid external service dependency.",
    },
    {
        id: "ADR-019",
        title: "REST API for all service communication",
        status: "superseded",
        createdAt: "2026-03-28T12:00:00Z",
        author: "arpit",
        summary: "Use RESTful HTTP for all inter-service communication. Superseded by ADR-024 (gRPC).",
    },
];

export const MOCK_COST_MODELS = [
    { model: "gpt-4o", provider: "OpenAI", accuracy: 94, avgCost: 0.032, cacheRate: 62, totalSpend: 18.40 },
    { model: "claude-sonnet", provider: "Anthropic", accuracy: 91, avgCost: 0.028, cacheRate: 58, totalSpend: 12.60 },
    { model: "gemini-2.0-flash", provider: "Google", accuracy: 82, avgCost: 0.001, cacheRate: 72, totalSpend: 3.20 },
    { model: "deepseek-chat", provider: "DeepSeek", accuracy: 79, avgCost: 0.0008, cacheRate: 65, totalSpend: 1.80 },
    { model: "gpt-4o-mini", provider: "OpenAI", accuracy: 85, avgCost: 0.004, cacheRate: 70, totalSpend: 4.50 },
    { model: "claude-haiku", provider: "Anthropic", accuracy: 78, avgCost: 0.002, cacheRate: 68, totalSpend: 2.10 },
];

export const MOCK_MEMORIES = [
    { id: "mem-1", concept: "TypeScript strict mode", type: "preference", confidence: 0.95, createdAt: "2026-04-09T16:20:00Z", content: "User prefers TypeScript strict mode enabled with noImplicitAny and strictNullChecks." },
    { id: "mem-2", concept: "Error handling pattern", type: "decision", confidence: 0.88, createdAt: "2026-04-08T12:00:00Z", content: "Always use try/catch with specific error types. Log errors before throwing." },
    { id: "mem-3", concept: "API versioning", type: "fact", confidence: 0.92, createdAt: "2026-04-07T10:00:00Z", content: "API uses /api/v1/ prefix. All new endpoints must follow this pattern." },
    { id: "mem-4", concept: "Database migrations", type: "preference", confidence: 0.90, createdAt: "2026-04-06T14:00:00Z", content: "Use Supabase migration files with timestamps. Never modify existing migrations." },
    { id: "mem-5", concept: "Code review criteria", type: "decision", confidence: 0.85, createdAt: "2026-04-05T11:00:00Z", content: "All PRs require council review for T2+ changes. T1 changes auto-approve with tests." },
];

export const MOCK_SKILLS = [
    { id: "skill-1", name: "Code Complexity Analyzer", status: "active", lastRun: "2026-04-09T15:00:00Z", description: "Analyzes code complexity metrics (cyclomatic, cognitive) and flags high-complexity functions.", triggers: ["on_push", "manual"] },
    { id: "skill-2", name: "Dependency Vulnerability Scanner", status: "active", lastRun: "2026-04-08T22:00:00Z", description: "Scans project dependencies for known vulnerabilities using OSV database.", triggers: ["daily", "on_push"] },
    { id: "skill-3", name: "API Documentation Generator", status: "inactive", lastRun: "2026-04-03T09:00:00Z", description: "Generates OpenAPI spec from FastAPI route definitions and docstrings.", triggers: ["manual"] },
    { id: "skill-4", name: "Test Coverage Reporter", status: "active", lastRun: "2026-04-09T18:00:00Z", description: "Runs pytest with coverage and reports uncovered lines.", triggers: ["on_push", "manual"] },
];
