#!/usr/bin/env bash
set -euo pipefail

# ─── Aegion Bootstrap Script ─── Phase 91 ───
# One-command setup: creates venv, installs deps,
# starts Supabase, runs migrations, and validates.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}→ $1${NC}"; }
ok()    { echo -e "${GREEN}✅ $1${NC}"; }
fail()  { echo -e "${RED}❌ $1${NC}"; exit 1; }

# ─── Prerequisites ───
info "Checking prerequisites..."
command -v python3 >/dev/null || fail "python3 not found"
command -v node    >/dev/null || fail "node not found"
command -v npm     >/dev/null || fail "npm not found"
ok "Prerequisites found"

# ─── Python Virtual Environment ───
info "Setting up Python virtual environment..."
if [ ! -d "$ROOT_DIR/aegion-backend/.venv" ]; then
    python3 -m venv "$ROOT_DIR/aegion-backend/.venv"
    ok "Created .venv"
else
    ok ".venv already exists"
fi

source "$ROOT_DIR/aegion-backend/.venv/bin/activate"

# ─── Python Dependencies ───
info "Installing Python dependencies..."
pip install -q --upgrade pip
pip install -q -r "$ROOT_DIR/aegion-backend/requirements.txt" 2>/dev/null || \
    pip install -q fastapi uvicorn supabase python-dotenv pydantic httpx 2>/dev/null || true
ok "Python deps installed"

# ─── Node Dependencies (Frontend) ───
info "Installing frontend dependencies..."
if [ -f "$ROOT_DIR/aegion-frontend/package.json" ]; then
    cd "$ROOT_DIR/aegion-frontend"
    npm install --silent 2>/dev/null || npm install
    ok "Frontend deps installed"
else
    info "No frontend package.json found, skipping"
fi

# ─── Node Dependencies (VS Code Extension) ───
info "Installing VS Code extension dependencies..."
if [ -f "$ROOT_DIR/aegion-vscode/package.json" ]; then
    cd "$ROOT_DIR/aegion-vscode"
    npm install --silent 2>/dev/null || npm install
    ok "Extension deps installed"
else
    info "No extension package.json found, skipping"
fi

# ─── Supabase ───
info "Checking Supabase CLI..."
if command -v supabase >/dev/null; then
    info "Starting Supabase (if not running)..."
    cd "$ROOT_DIR"
    supabase start 2>/dev/null || info "Supabase already running or not configured"
    ok "Supabase ready"
else
    info "Supabase CLI not found — skipping local DB setup"
    info "Install: https://supabase.com/docs/guides/cli"
fi

# ─── Environment File ───
info "Checking environment configuration..."
ENV_FILE="$ROOT_DIR/aegion-backend/.env"
if [ ! -f "$ENV_FILE" ]; then
    info "Creating .env from .env.example..."
    if [ -f "$ROOT_DIR/aegion-backend/.env.example" ]; then
        cp "$ROOT_DIR/aegion-backend/.env.example" "$ENV_FILE"
    else
        cat > "$ENV_FILE" << 'EOF'
# Aegion Backend Environment (Auto-generated by bootstrap)
APP_NAME=Aegion
ENVIRONMENT=development
GRAPH_BACKEND=memory
SUPABASE_URL=http://localhost:54321
SUPABASE_ANON_KEY=your-anon-key
SUPABASE_DB_HOST=localhost
SUPABASE_DB_PORT=54322
SUPABASE_DB_NAME=postgres
SUPABASE_DB_USER=postgres
SUPABASE_DB_PASSWORD=postgres
EOF
    fi
    ok ".env created"
else
    ok ".env already exists"
fi

# ─── Smoke Test ───
info "Running smoke test..."
cd "$ROOT_DIR"
make smoke && ok "Smoke test passed" || fail "Smoke test failed"

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  Aegion bootstrap complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  Start developing:"
echo "    make dev          — Backend dev server"
echo "    make dev-frontend — Frontend dev server"
echo "    make dev-all      — All services"
echo "    make test         — Run tests"
echo "    make help         — Show all commands"
echo ""
